# This job needs 1 compute node with 1 processor per node.
# #PBS -l nodes=node547.cluster:ppn=1,pmem=8gb,pvmem=9gb
#PBS -l nodes=1:ppn=1,pmem=8gb,pvmem=9gb
# It should be allowed to run for up to 30min.
#PBS -l walltime=30:00:00
# Name of job.
#PBS -N foamEnsembleRun
# Join STDERR TO STDOUT.  (omit this if you want separate STDOUT AND STDERR)
#PBS -j oe

echo "PBS_O_HOST=${PBS_O_HOST}"
echo "PBS_SERVER=${PBS_SERVER}"
echo "PBS_NODEFILE=${PBS_NODEFILE}"

echo "currdir=$(pwd)"
cd /users/a/r/areagan/work/2014/11-julia-openfoam
echo "currdir=$(pwd)"

echo "julia version:"
which julia

/usr/bin/time -v julia runEnsemble.jl