# This job needs 1 compute node with 8 processor per node.
#PBS -l nodes=1:ppn=8,pmem=2gb,pvmem=2gb

# It should be allowed to run for up to 30min.
#PBS -l walltime=30:00:00

# Name of job.
#PBS -N foamEnsembleRun

# Join STDERR TO STDOUT
#PBS -j oe

# Look at some of the environment action from PBS

echo "PBS_O_HOST=${PBS_O_HOST}"
echo "PBS_SERVER=${PBS_SERVER}"
echo "PBS_NODEFILE=${PBS_NODEFILE}"
echo "PBS_NP=$PBS_NP"

echo "----------------------------------------"
echo "----------------------------------------"
env 
echo "----------------------------------------"
echo "----------------------------------------"

cd $PBS_O_WORKDIR 

echo "julia version:"
which julia

# julia -p "$(($PBS_NP-1))"
# julia -p 7 runEnsemble.jl "parallel-001" "0" "100" "10" "2000" "0" "1" "1" "20"
# julia -p 7 runEnsemble.jl "bigtest-001" "0" "100" "10" "2000" "0" "1" "1" "20"
julia -p 7 runEnsemble.jl "bigtest-$(printf "%05d\n" ${TEST})" "0" "100" "10" "2000" "${SHIFT}" "${OBS_SPACING}" "0" "20"




