# This job needs 1 compute node with 1 processor per node.
# #PBS -l nodes=node547.cluster:ppn=1,pmem=8gb,pvmem=9gb
#PBS -l nodes=1:ppn=1,pmem=8gb,pvmem=9gb

# It should be allowed to run for up to 30min.
#PBS -l walltime=30:00:00

# Name of job.
#PBS -N foamEnsembleRun

# Join STDERR TO STDOUT.  (omit this if you want separate STDOUT AND STDERR)
#PBS -j oe

echo "PBS_O_HOST=${PBS_O_HOST}"
echo "PBS_SERVER=${PBS_SERVER}"
echo "PBS_NODEFILE=${PBS_NODEFILE}"
echo "PBS_NP=$PBS_NP"

echo "----------------------------------------"
echo "----------------------------------------"
env 
echo "----------------------------------------"
echo "----------------------------------------"

cd $PBS_O_WORKDIR 

echo "julia version:"
which julia

# julia -p 0 runEnsemble.jl "lessobs-001" "0" "100" "10" "200" "0" "5" "1" "20"
# julia -p 0 runEnsemble.jl "lessobs-002" "0" "100" "10" "200" "0" "10" "1" "20"
# julia -p 0 runEnsemble.jl "lessobs-003" "0" "100" "10" "200" "0" "20" "1" "20"
# julia -p 0 runEnsemble.jl "sliding-001" "0" "100" "10" "200" "2" "1" "1" "20"
# julia -p 0 runEnsemble.jl "sliding-002" "0" "100" "10" "200" "5" "1" "1" "20"
julia -p 0 runEnsemble.jl "sliding-003" "0" "100" "10" "200" "10" "1" "1" "20"

